using FluentMigrator;

namespace Infrastructure.Database.Migrations;

[Migration(2, description: "Create ratings table")]
public class CreateRatings : Migration
{
    public override void Up()
    {
        Execute.Sql($"""
                     CREATE TABLE ratings (
                         rating_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         subject_id         BIGINT NOT NULL,
                         subject_type       subject_type DEFAULT 'unknown',
                         rater_id           BIGINT NOT NULL,
                         stars              NUMERIC(3,2) NOT NULL DEFAULT 5.00,
                         comment            varchar(100) NOT NULL DEFAULT '',
                         created_at         TIMESTAMP NOT NULL DEFAULT now()
                     );
                     """);
    }

    public override void Down()
    {
        Execute.Sql("""
                    DROP TABLE IF EXISTS ratings;
                    """);
    }
}